version: "3"

services:
  web:
    # image: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}"
    build:
      context: .
    environment:
      DEBUG: True
    ports:
      - 8001:8000
    depends_on:
      - db  

  db:
    image: postgres:15.4
    ports:
     - "5342:5342"
    volumes:
      - djshop-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=djshop
      - PSTGRES_USER=djad
      - POSTGRES_PASSWORD=p@SSW0RD



# # version: '3.7'

# # services:
# #   app:
# #     build:
# #       context: .
# #       command: > 
# #         bash -c "python manage.py migrate &&
# #                  python manage.py runsever 0.0.0.0:8000"
# #     ports:
# #       - "8000:8000"
# #     volumes:
# #        - ./src:/src
# #        - ./data/web:/vol/web

# #     depends_on:
# #       - db      


# #   db:
# #     image: postgres:15.4
# #     ports:
# #       - "5342:5342"
# #     volumes:
# #       - djshop-data:/var/lib/postgresql/data
# #     environment:
# #       - POSTGRES_DB=djshop
# #       - PSTGRES_USER=djad
# #       - POSTGRES_PASSWORD=p@SSW0RD

# # volumes:
# #   djshop-data:       

# version: '3'

# services:
#   app:
#     build: .
#     command: > 
#       bash -c "python manage.py makemigrations && python manage.py migrate &&
#                python manage.py runsever 0.0.0.0:8000"
#     volumes:
#       - .:/src
#     ports:
#       - "8000:8000"



#   db:
#     image: "postgres:14.1-alpine"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     ports:
#       - "5342:5342"  
#     environment:
#       - POSTGRES_DB=djshop
#       - PSTGRES_USER=djad 
#       - POSTGRES_PASSWORD=p@SSW0RD

# volumes:
#   postgres_data:
# version: "3.9"

# services:
#   web:
#     build: .
#     volumes:
#       - .:/code
#     ports:
#       - 8001:8000